services:
  postgress:
    image: postgres:15-alpine
    container_name: be-postgres
    environment:
      POSTGRES_DB: park
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testtest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: